version: '3.8'

services:
  db:
    image: postgres:17
    restart: always
    environment:
      POSTGRES_DB: filmoteka_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - .docker/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - filmoteka-network
  
  api:
    build:
      context: .
      dockerfile: Api/Dockerfile
    ports:
      - "7181:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    depends_on:
      - db
    networks:
      - filmoteka_network
  
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - api
    networks:
      - filmoteka-network

volumes:
  postgres_

networks:
  filmoteka-network:
    driver: bridge